export const factorDatas = {
  status: "ステータス因子",
  appropriate: "適正因子",
  uniqueSkill: "固有スキル",
  G1: "レース因子",
  skill: "通常因子",
} as const;
export type FactorTypes = keyof typeof factorDatas;
export type Factor = {
  id: string;
  name: string;
  type: FactorTypes;
  desc: string;
  star?: 1 | 2 | 3;
  checked?: boolean;
};
export const factors: Factor[] = [
  {
    id: "speed",
    name: "スピード",
    type: "status",
    desc: "スピードがアップする因子です",
  },
  {
    id: "stamina",
    name: "スタミナ",
    type: "status",
    desc: "スタミナがアップする因子です",
  },
  {
    id: "power",
    name: "パワー",
    type: "status",
    desc: "パワーがアップする因子です",
  },
  {
    id: "konjo",
    name: "根性",
    type: "status",
    desc: "根性がアップする因子です",
  },
  {
    id: "kashikosa",
    name: "賢さ",
    type: "status",
    desc: "賢さがアップする因子です",
  },
  {
    id: "tankyori",
    name: "短距離",
    type: "status",
    desc: "短距離適性がアップする因子です",
  },
  {
    id: "mile",
    name: "マイル",
    type: "appropriate",
    desc: "マイル適性がアップする因子です",
  },
  {
    id: "tyukyori",
    name: "中距離",
    type: "appropriate",
    desc: "中距離適性がアップする因子です",
  },
  {
    id: "tyokyori",
    name: "長距離",
    type: "appropriate",
    desc: "長距離適性がアップする因子です",
  },
  {
    id: "nige",
    name: "逃げ",
    type: "appropriate",
    desc: "逃げ適性がアップする因子です",
  },
  {
    id: "senko",
    name: "先行",
    type: "appropriate",
    desc: "先行適性がアップする因子です",
  },
  {
    id: "sashi",
    name: "差し",
    type: "appropriate",
    desc: "差し適性がアップする因子です",
  },
  {
    id: "oikomi",
    name: "追込",
    type: "appropriate",
    desc: "追込適性がアップする因子です",
  },
  {
    id: "red_ace",
    name: "レッドエース",
    type: "uniqueSkill",
    desc: "「レッドエース」のスキルヒントを得られる因子です",
  },
  {
    id: "win_kiss",
    name: "勝利のキッス☆",
    type: "uniqueSkill",
    desc: "「勝利のキッス☆」のスキルヒントを得られる因子です",
  },
  {
    id: "accell_X",
    name: "アクセルX",
    type: "uniqueSkill",
    desc: "「アクセルX」のスキルヒントを得られる因子です",
  },
  {
    id: "haran_caution",
    name: "波乱注意砲！",
    type: "uniqueSkill",
    desc: "「波乱注意砲！」のスキルヒントを得られる因子です",
  },
  {
    id: "call_me_king",
    name: "Call me KING",
    type: "uniqueSkill",
    desc: "「Call me KING」のスキルヒントを得られる因子です",
  },
  {
    id: "atashimo_tamaniha_ne",
    name: "アタシもたまには、ね？",
    type: "uniqueSkill",
    desc: "「アタシもたまには、ね？」のスキルヒントを得られる因子です",
  },
  {
    id: "double_kitekudasai",
    name: "来てください来てください！",
    type: "uniqueSkill",
    desc: "「来てください来てください！」のスキルヒントを得られる因子です",
  },
  {
    id: "iintyo_speed_bakushin",
    name: "学級委員長＋早さ＝バクシン",
    type: "uniqueSkill",
    desc: "「学級委員長＋早さ＝バクシン」のスキルヒントを得られる因子です",
  },
  {
    id: "zenryoku_V",
    name: "全力Vサインッ！",
    type: "uniqueSkill",
    desc: "「全力Vサインッ！」のスキルヒントを得られる因子です",
  },
  {
    id: "enbless_pride",
    name: "エンプレス・プライド",
    type: "uniqueSkill",
    desc: "「エンプレス・プライド」のスキルヒントを得られる因子です",
  },
  {
    id: "nekketsu_amigo",
    name: "熱血☆アミーゴ",
    type: "uniqueSkill",
    desc: "「熱血☆アミーゴ」のスキルヒントを得られる因子です",
  },
  {
    id: "win_heart",
    name: "勝利の鼓動",
    type: "uniqueSkill",
    desc: "「勝利の鼓動」のスキルヒントを得られる因子です",
  },
  {
    id: "ultimate_teioh_step",
    name: "究極テイオーステップ",
    type: "uniqueSkill",
    desc: "「究極テイオーステップ」のスキルヒントを得られる因子です",
  },
  {
    id: "shime_hatasu",
    name: "貴顕の使命を果たすべく",
    type: "uniqueSkill",
    desc: "「貴顕の使命を果たすべく」のスキルヒントを得られる因子です",
  },
  {
    id: "nanji_shini",
    name: "汝、皇帝の神威を見よ",
    type: "uniqueSkill",
    desc: "「汝、皇帝の神威を見よ」のスキルヒントを得られる因子です",
  },
  {
    id: "sento_no_keshiki",
    name: "先頭の景色は譲らない･･･！",
    type: "uniqueSkill",
    desc: "「先頭の景色は譲らない･･･！」のスキルヒントを得られる因子です",
  },
  {
    id: "blu_rose_chaiser",
    name: "ブルーローズチェイサー",
    type: "uniqueSkill",
    desc: "「ブルーローズチェイサー」のスキルヒントを得られる因子です",
  },
  {
    id: "shooting_star",
    name: "シューティングスター",
    type: "uniqueSkill",
    desc: "「シューティングスター」のスキルヒントを得られる因子です",
  },
  {
    id: "moero_mattyo",
    name: "燃えろ筋肉！",
    type: "uniqueSkill",
    desc: "「燃えろ筋肉！」のスキルヒントを得られる因子です",
  },
  {
    id: "LP1211_M",
    name: "紅焔ギア/LP1211-M",
    type: "uniqueSkill",
    desc: "「紅焔ギア/LP1211-M」のスキルヒントを得られる因子です",
  },
  {
    id: "victory_shot",
    name: "ヴィクトリーショット",
    type: "uniqueSkill",
    desc: "「ヴィクトリーショット」のスキルヒントを得られる因子です",
  },
  {
    id: "pyurity_of_heart",
    name: "ピュリティオブハート",
    type: "uniqueSkill",
    desc: "「ピュリティオブハート」のスキルヒントを得られる因子です",
  },
  {
    id: "wakuwaku_yoi_don",
    name: "ワクワクよーいドン",
    type: "uniqueSkill",
    desc: "「ワクワクよーいドン」のスキルヒントを得られる因子です",
  },
  {
    id: "introduction_Mybody",
    name: "introduction：Mybody",
    type: "uniqueSkill",
    desc: "「introduction：Mybody」のスキルヒントを得られる因子です",
  },
  {
    id: "clear_heart",
    name: "クリアハート",
    type: "uniqueSkill",
    desc: "「クリアハート」のスキルヒントを得られる因子です",
  },
  {
    id: "vittoria_buto",
    name: "ヴィットーリアに捧ぐ舞踏",
    type: "uniqueSkill",
    desc: "「ヴィットーリアに捧ぐ舞踏」のスキルヒントを得られる因子です",
  },
  {
    id: "hanshin_JF",
    name: "阪神JF",
    type: "G1",
    desc: "スピードとパワーがアップする因子です",
  },
  {
    id: "asahihai_FS",
    name: "朝日杯FS",
    type: "G1",
    desc: "スピードと根性がアップする因子です",
  },
  {
    id: "hopefull_S",
    name: "ホープフルS",
    type: "G1",
    desc: "スピードとスタミナがアップする因子です",
  },
  {
    id: "oka_cup",
    name: "桜花賞",
    type: "G1",
    desc: "根性がアップし、「阪神レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "satsuki_cup",
    name: "皐月賞",
    type: "G1",
    desc: "パワーがアップし、「中山レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "NHK_mile_C",
    name: "NHKマイルC",
    type: "G1",
    desc: "スピードとスタミナがアップする因子です",
  },
  {
    id: "okes",
    name: "オークス",
    type: "G1",
    desc:
      "スタミナがアップし、「東京レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "japan_derby",
    name: "日本ダービー",
    type: "G1",
    desc: "根性がアップし、「東京レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "yasuda_",
    name: "安田記念",
    type: "G1",
    desc:
      "スピードがアップし、「東京レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "takaraduka",
    name: "宝塚記念",
    type: "G1",
    desc: "根性がアップし、「夏ウマ娘○」のスキルヒントを得られる因子です",
  },
  {
    id: "japan_dart_derby",
    name: "ジャパンダートダービー",
    type: "G1",
    desc: "パワーがアップし、「大井レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "sprinters_S",
    name: "スプリンターズS",
    type: "G1",
    desc: "スピードがアップし、「根幹距離○」のスキルヒントを得られる因子です",
  },
  {
    id: "kikka_cup",
    name: "菊花賞",
    type: "G1",
    desc:
      "スタミナがアップし、「京都レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "syuka_cup",
    name: "秋華賞",
    type: "G1",
    desc: "賢さがアップし、「京都レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "tenno_autum",
    name: "天皇賞(秋)",
    type: "G1",
    desc: "スピードがアップし、「秋ウマ娘○」のスキルヒントを得られる因子です",
  },
  {
    id: "JBS_redies",
    name: "JBCレディスクラシック",
    type: "G1",
    desc: "スピードと根性がアップする因子です",
  },
  {
    id: "JBS_classic",
    name: "JBCクラシック",
    type: "G1",
    desc: "スピードと根性がアップする因子です",
  },
  {
    id: "JBS_sprint",
    name: "JBCスプリント",
    type: "G1",
    desc: "パワーと根性がアップする因子です",
  },
  {
    id: "elizabeth_cup",
    name: "エリザベス女王杯",
    type: "G1",
    desc: "スタミナがアップし、「非根幹距離○」のスキルヒントを得られる因子です",
  },
  {
    id: "japan_C",
    name: "ジャパンC",
    type: "G1",
    desc:
      "スタミナがアップし、「東京レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "mile_CS",
    name: "マイルCS",
    type: "G1",
    desc: "スピードがアップし、「根幹距離○」のスキルヒントを得られる因子です",
  },
  {
    id: "chanpions_C",
    name: "チャンピオンズC",
    type: "G1",
    desc: "パワーがアップし、「中京レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "arima",
    name: "有馬記念",
    type: "G1",
    desc: "根性がアップし、「中山レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "tokyo_daishoten",
    name: "東京大賞典",
    type: "G1",
    desc: "パワーがアップし、「大井レース場◯」のスキルヒントを得られる因子です",
  },
  {
    id: "febrary_S",
    name: "フェブラリーS",
    type: "G1",
    desc: "パワーがアップし、「冬ウマ娘○」のスキルヒントを得られる因子です",
  },
  {
    id: "takamatsunomiya",
    name: "高松宮記念",
    type: "G1",
    desc:
      "スピードがアップし、「中京レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "osaka_cup",
    name: "大阪杯",
    type: "G1",
    desc: "根性がアップし、「根幹距離○」のスキルヒントを得られる因子です",
  },
  {
    id: "tenno_spring",
    name: "天皇賞(春)",
    type: "G1",
    desc: "スタミナがアップし、「春ウマ娘○」のスキルヒントを得られる因子です",
  },
  {
    id: "victoria_mile",
    name: "ヴィクトリアマイル",
    type: "G1",
    desc: "スピードとパワーがアップする因子です",
  },
  {
    id: "URA_sinario",
    name: "URAシナリオ",
    type: "G1",
    desc: "スピードとスタミナがアップする因子です",
  },
  {
    id: "teioh",
    name: "帝王賞",
    type: "G1",
    desc: "パワーがアップし、「大井レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "cool_down",
    name: "クールダウン",
    type: "skill",
    desc: "「クールダウン」のスキルヒントを得られる因子です",
  },
  {
    id: "pase_up",
    name: "ペースアップ",
    type: "skill",
    desc: "「ペースアップ」のスキルヒントを得られる因子です",
  },
  {
    id: "makenki",
    name: "負けん気",
    type: "skill",
    desc: "「負けん気」のスキルヒントを得られる因子です",
  },
  {
    id: "mile_corner_1",
    name: "マイルコーナー◯",
    type: "skill",
    desc: "「マイルコーナー◯」のスキルヒントを得られる因子です",
  },
  {
    id: "sashi_tyokusen_1",
    name: "差し直線◯",
    type: "skill",
    desc: "「差し直線◯」のスキルヒントを得られる因子です",
  },
  {
    id: "oikomi_tyokusen_1",
    name: "追込直線◯",
    type: "skill",
    desc: "「追込直線◯」のスキルヒントを得られる因子です",
  },
  {
    id: "shikake_batsugun",
    name: "仕掛け抜群",
    type: "skill",
    desc: "「仕掛け抜群」のスキルヒントを得られる因子です",
  },
  {
    id: "oikomi_corner_1",
    name: "追込コーナー◯",
    type: "skill",
    desc: "「追込コーナー◯」のスキルヒントを得られる因子です",
  },
  {
    id: "sashi_corner_1",
    name: "差しコーナー◯",
    type: "skill",
    desc: "「差しコーナー◯」のスキルヒントを得られる因子です",
  },
  {
    id: "asobiha_oshimai",
    name: "遊びはおしまいっ！",
    type: "skill",
    desc: "「遊びはおしまいっ！」のスキルヒントを得られる因子です",
  },
  {
    id: "zengosaku",
    name: "善後策",
    type: "skill",
    desc: "「善後策」のスキルヒントを得られる因子です",
  },
  {
    id: "srip_stream",
    name: "スリップストリーム",
    type: "skill",
    desc: "「スリップストリーム」のスキルヒントを得られる因子です",
  },
  {
    id: "okina_rido",
    name: "大きなリード",
    type: "skill",
    desc: "「大きなリード」のスキルヒントを得られる因子です",
  },
  {
    id: "mile_tyokusen_1",
    name: "マイル直線◯",
    type: "skill",
    desc: "「マイル直線◯」のスキルヒントを得られる因子です",
  },
  {
    id: "speed_star",
    name: "スピードスター",
    type: "skill",
    desc: "「スピードスター」のスキルヒントを得られる因子です",
  },
  {
    id: "gia_shift",
    name: "ギアシフト",
    type: "skill",
    desc: "「ギアシフト」のスキルヒントを得られる因子です",
  },
  {
    id: "tankyori_corner_1",
    name: "短距離コーナー◯",
    type: "skill",
    desc: "「短距離コーナー◯」のスキルヒントを得られる因子です",
  },
  {
    id: "sekkyoku_saku",
    name: "積極策",
    type: "skill",
    desc: "「積極策」のスキルヒントを得られる因子です",
  },
  {
    id: "nige_aseri",
    name: "逃げ焦り",
    type: "skill",
    desc: "「逃げ焦り」のスキルヒントを得られる因子です",
  },
  {
    id: "tyokusen_koja",
    name: "直線巧者",
    type: "skill",
    desc: "「直線巧者」のスキルヒントを得られる因子です",
  },
  {
    id: "sakigake",
    name: "先駆け",
    type: "skill",
    desc: "「先駆け」のスキルヒントを得られる因子です",
  },
  {
    id: "sueashi",
    name: "未脚",
    type: "skill",
    desc: "「未脚」のスキルヒントを得られる因子です",
  },
  {
    id: "rido_keep",
    name: "リードキープ",
    type: "skill",
    desc: "「リードキープ」のスキルヒントを得られる因子です",
  },
  {
    id: "juman_bariki",
    name: "十万バリキ",
    type: "skill",
    desc: "「十万バリキ」のスキルヒントを得られる因子です",
  },
  {
    id: "tyukyori_corner_1",
    name: "中距離コーナー◯",
    type: "skill",
    desc: "「中距離コーナー◯」のスキルヒントを得られる因子です",
  },
  {
    id: "tyokyori_corner_1",
    name: "長距離コーナー◯",
    type: "skill",
    desc: "「長距離コーナー◯」のスキルヒントを得られる因子です",
  },
  {
    id: "senko_corner_1",
    name: "先行コーナー◯",
    type: "skill",
    desc: "「先行コーナー◯」のスキルヒントを得られる因子です",
  },
  {
    id: "killer_tune",
    name: "キラーチューン",
    type: "skill",
    desc: "「キラーチューン」のスキルヒントを得られる因子です",
  },
  {
    id: "oshikiri_junbi",
    name: "押し切り準備",
    type: "skill",
    desc: "「押し切り準備」のスキルヒントを得られる因子です",
  },
  {
    id: "tempo_up",
    name: "テンポアップ",
    type: "skill",
    desc: "「テンポアップ」のスキルヒントを得られる因子です",
  },
  {
    id: "nukedashi_junbi",
    name: "抜け出し準備",
    type: "skill",
    desc: "「抜け出し準備」のスキルヒントを得られる因子です",
  },
  {
    id: "kcorner_koja_1",
    name: "コーナー巧者◯",
    type: "skill",
    desc: "「コーナー巧者◯」のスキルヒントを得られる因子です",
  },
  {
    id: "tetei_mark_1",
    name: "徹底マーク◯",
    type: "skill",
    desc: "「徹底マーク◯」のスキルヒントを得られる因子です",
  },
  {
    id: "tankyori_tyokusen_1",
    name: "短距離直線◯",
    type: "skill",
    desc: "「短距離直線◯」のスキルヒントを得られる因子です",
  },
  {
    id: "ititori_oshiage",
    name: "位置取り押し上げ",
    type: "skill",
    desc: "「位置取り押し上げ」のスキルヒントを得られる因子です",
  },
  {
    id: "shikake_junbi",
    name: "仕掛け準備",
    type: "skill",
    desc: "「仕掛け準備」のスキルヒントを得られる因子です",
  },
  {
    id: "tsumeyori",
    name: "詰め寄り",
    type: "skill",
    desc: "「詰め寄り」のスキルヒントを得られる因子です",
  },
  {
    id: "kuisagari",
    name: "食い下がり",
    type: "skill",
    desc: "「食い下がり」のスキルヒントを得られる因子です",
  },
  {
    id: "tyukyori_tyokusen",
    name: "中距離直線◯",
    type: "skill",
    desc: "「中距離直線◯」のスキルヒントを得られる因子です",
  },
  {
    id: "sotozashi_junbi",
    name: "外差し準備",
    type: "skill",
    desc: "「外差し準備」のスキルヒントを得られる因子です",
  },
  {
    id: "sueashi",
    name: "末脚",
    type: "skill",
    desc: "「末脚」のスキルヒントを得られる因子です",
  },
  {
    id: "sippo_agari",
    name: "尻尾上がり",
    type: "skill",
    desc: "「尻尾上がり」のスキルヒントを得られる因子です",
  },
  {
    id: "uma_gonomi",
    name: "ウマ好み",
    type: "skill",
    desc: "「ウマ好み」のスキルヒントを得られる因子です",
  },
  {
    id: "oiage",
    name: "追い上げ",
    type: "skill",
    desc: "「追い上げ」のスキルヒントを得られる因子です",
  },
  {
    id: "uchibenke",
    name: "内弁慶",
    type: "skill",
    desc: "「内弁慶」のスキルヒントを得られる因子です",
  },
  {
    id: "senko_tyokusen_1",
    name: "先行直線◯",
    type: "skill",
    desc: "「先行直線◯」のスキルヒントを得られる因子です",
  },
  {
    id: "sento_pride",
    name: "先頭プライド",
    type: "skill",
    desc: "「先頭プライド」のスキルヒントを得られる因子です",
  },
  {
    id: "nige_corner_1",
    name: "逃げコーナー◯",
    type: "skill",
    desc: "「逃げコーナー◯」のスキルヒントを得られる因子です",
  },
  {
    id: "nige_tyokusen_1",
    name: "逃げ直線◯",
    type: "skill",
    desc: "「逃げ直線◯」のスキルヒントを得られる因子です",
  },
  {
    id: "inaduma_step",
    name: "イナズマステップ",
    type: "skill",
    desc: "「イナズマステップ」のスキルヒントを得られる因子です",
  },
  {
    id: "rinki_ohen",
    name: "臨機応変",
    type: "skill",
    desc: "「臨機応変」のスキルヒントを得られる因子です",
  },
  {
    id: "position_sense",
    name: "ポジションセンス",
    type: "skill",
    desc: "「ポジションセンス」のスキルヒントを得られる因子です",
  },
  {
    id: "ganbariya",
    name: "がんばり屋",
    type: "skill",
    desc: "「がんばり屋」のスキルヒントを得られる因子です",
  },
  {
    id: "makinaoshi",
    name: "まき直し",
    type: "skill",
    desc: "「まき直し」のスキルヒントを得られる因子です",
  },
  {
    id: "tyokyori_tyokusen_1",
    name: "長距離直線◯",
    type: "skill",
    desc: "「長距離直線◯」のスキルヒントを得られる因子です",
  },
  {
    id: "tareuma_kaihi",
    name: "垂れウマ回避",
    type: "skill",
    desc: "「垂れウマ回避」のスキルヒントを得られる因子です",
  },
  {
    id: "corner_kasoku_1",
    name: "コーナー加速◯",
    type: "skill",
    desc: "「コーナー加速◯」のスキルヒントを得られる因子です",
  },
  {
    id: "accelaration",
    name: "アクセラレーション",
    type: "skill",
    desc: "「アクセラレーション」のスキルヒントを得られる因子です",
  },
  {
    id: "sprint_gear",
    name: "スプリントギア",
    type: "skill",
    desc: "「スプリントギア」のスキルヒントを得られる因子です",
  },
  {
    id: "takumina_step",
    name: "巧みなステップ",
    type: "skill",
    desc: "「巧みなステップ」のスキルヒントを得られる因子です",
  },
  {
    id: "dassyutsu_jutsu",
    name: "脱出術",
    type: "skill",
    desc: "「脱出術」のスキルヒントを得られる因子です",
  },
  {
    id: "ninoya",
    name: "二の矢",
    type: "skill",
    desc: "「二の矢」のスキルヒントを得られる因子です",
  },
  {
    id: "isogi_ashi",
    name: "急ぎ足",
    type: "skill",
    desc: "「急ぎ足」のスキルヒントを得られる因子です",
  },
  {
    id: "tozanka",
    name: "登山家",
    type: "skill",
    desc: "「登山家」のスキルヒントを得られる因子です",
  },
  {
    id: "tyokkakko",
    name: "直滑降",
    type: "skill",
    desc: "「直滑降」のスキルヒントを得られる因子です",
  },
  {
    id: "joshokiryu",
    name: "上昇気流",
    type: "skill",
    desc: "「上昇気流」のスキルヒントを得られる因子です",
  },
  {
    id: "sashikiri_taisei",
    name: "差し切り体勢",
    type: "skill",
    desc: "「差し切り体勢」のスキルヒントを得られる因子です",
  },
  {
    id: "tyokusen_kasoku",
    name: "直線加速",
    type: "skill",
    desc: "「直線加速」のスキルヒントを得られる因子です",
  },
  {
    id: "digatame",
    name: "地固め",
    type: "skill",
    desc: "「地固め」のスキルヒントを得られる因子です",
  },
  {
    id: "tyokusen_ikki",
    name: "直線一気",
    type: "skill",
    desc: "「直線一気」のスキルヒントを得られる因子です",
  },
  {
    id: "dokkairyoku",
    name: "読解力",
    type: "skill",
    desc: "「読解力」のスキルヒントを得られる因子です",
  },
  {
    id: "hoak_eye",
    name: "ホークアイ",
    type: "skill",
    desc: "「ホークアイ」のスキルヒントを得られる因子です",
  },
  {
    id: "sakushi",
    name: "策士",
    type: "skill",
    desc: "「策士」のスキルヒントを得られる因子です",
  },
  {
    id: "omitoshi",
    name: "お見通し",
    type: "skill",
    desc: "「お見通し」のスキルヒントを得られる因子です",
  },
  {
    id: "shutyuryoku",
    name: "集中力",
    type: "skill",
    desc: "「集中力」のスキルヒントを得られる因子です",
  },
  {
    id: "oikomi_tamerai",
    name: "追込ためらい",
    type: "skill",
    desc: "「追込ためらい」のスキルヒントを得られる因子です",
  },
  {
    id: "nige_tamerai",
    name: "逃げためらい",
    type: "skill",
    desc: "「逃げためらい」のスキルヒントを得られる因子です",
  },
  {
    id: "fuseki",
    name: "布石",
    type: "skill",
    desc: "「布石」のスキルヒントを得られる因子です",
  },
  {
    id: "sashi_tamerai",
    name: "差しためらい",
    type: "skill",
    desc: "「差しためらい」のスキルヒントを得られる因子です",
  },
  {
    id: "koho_kugiduke",
    name: "後方釘付",
    type: "skill",
    desc: "「後方釘付」のスキルヒントを得られる因子です",
  },
  {
    id: "senko_tamerai",
    name: "先行ためらい",
    type: "skill",
    desc: "「先行ためらい」のスキルヒントを得られる因子です",
  },
  {
    id: "sokubaku",
    name: "束縛",
    type: "skill",
    desc: "「束縛」のスキルヒントを得られる因子です",
  },
  {
    id: "manazashi",
    name: "まなざし",
    type: "skill",
    desc: "「まなざし」のスキルヒントを得られる因子です",
  },
  {
    id: "sasayaki",
    name: "ささやき",
    type: "skill",
    desc: "「ささやき」のスキルヒントを得られる因子です",
  },
  {
    id: "nukegake_kinshi",
    name: "抜け駆け禁止",
    type: "skill",
    desc: "「抜け駆け禁止」のスキルヒントを得られる因子です",
  },
  {
    id: "oikomi_aseri",
    name: "追込焦り",
    type: "skill",
    desc: "「追込焦り」のスキルヒントを得られる因子です",
  },
  {
    id: "nige_kense",
    name: "逃げけん制",
    type: "skill",
    desc: "「逃げけん制」のスキルヒントを得られる因子です",
  },
  {
    id: "oikomi_kakehiki",
    name: "追込駆け引き",
    type: "skill",
    desc: "「追込駆け引き」のスキルヒントを得られる因子です",
  },
  {
    id: "oikomi_kense",
    name: "追込けん制",
    type: "skill",
    desc: "「追込けん制」のスキルヒントを得られる因子です",
  },
  {
    id: "trick_ato",
    name: "トリック(後)",
    type: "skill",
    desc: "「トリック(後)」のスキルヒントを得られる因子です",
  },
  {
    id: "stamina_eater",
    name: "スタミナイーター",
    type: "skill",
    desc: "「スタミナイーター」のスキルヒントを得られる因子です",
  },
  {
    id: "speed_eater",
    name: "スピードイーター",
    type: "skill",
    desc: "「スピードイーター」のスキルヒントを得られる因子です",
  },
  {
    id: "sashi_aseri",
    name: "差し焦り",
    type: "skill",
    desc: "「差し焦り」のスキルヒントを得られる因子です",
  },
  {
    id: "restart",
    name: "リスタート",
    type: "skill",
    desc: "「リスタート」のスキルヒントを得られる因子です",
  },
  {
    id: "trick_mae",
    name: "トリック(前)",
    type: "skill",
    desc: "「トリック(前)」のスキルヒントを得られる因子です",
  },
  {
    id: "sashi_kensei",
    name: "差しけん制",
    type: "skill",
    desc: "「差しけん制」のスキルヒントを得られる因子です",
  },
  {
    id: "nukegake_kinshi",
    name: "抜け駆け禁止",
    type: "skill",
    desc: "「抜け駆け禁止」のスキルヒントを得られる因子です",
  },
  {
    id: "senko_aseri",
    name: "先行焦り",
    type: "skill",
    desc: "「先行焦り」のスキルヒントを得られる因子です",
  },
  {
    id: "senko_kensei",
    name: "先行けん制",
    type: "skill",
    desc: "「先行けん制」のスキルヒントを得られる因子です",
  },
  {
    id: "surudoi_ganko",
    name: "鋭い眼光",
    type: "skill",
    desc: "「鋭い眼光」のスキルヒントを得られる因子です",
  },
  {
    id: "nige_kakehiki",
    name: "逃げ駆け引き",
    type: "skill",
    desc: "「逃げ駆け引き」のスキルヒントを得られる因子です",
  },
  {
    id: "sashi_kakehiki",
    name: "差し駆け引き",
    type: "skill",
    desc: "「差し駆け引き」のスキルヒントを得られる因子です",
  },
  {
    id: "senko_kakehiki",
    name: "先行駆け引き",
    type: "skill",
    desc: "「先行駆け引き」のスキルヒントを得られる因子です",
  },
  {
    id: "kakuran",
    name: "かく乱",
    type: "skill",
    desc: "「かく乱」のスキルヒントを得られる因子です",
  },
  {
    id: "mekuramashi",
    name: "目くらまし",
    type: "skill",
    desc: "「目くらまし」のスキルヒントを得られる因子です",
  },
  {
    id: "kokura_race_1",
    name: "小倉レース場◯",
    type: "skill",
    desc: "「小倉レース場◯」のスキルヒントを得られる因子です",
  },
  {
    id: "hi_konkan_1",
    name: "非根幹距離◯",
    type: "skill",
    desc: "「非根幹距離◯」のスキルヒントを得られる因子です",
  },
  {
    id: "kyoto_race_1",
    name: "京都レース場◯",
    type: "skill",
    desc: "「京都レース場◯」のスキルヒントを得られる因子です",
  },
  {
    id: "hakodate_race_1",
    name: "函館レース場◯",
    type: "skill",
    desc: "「函館レース場◯」のスキルヒントを得られる因子です",
  },
  {
    id: "sapporo_race_1",
    name: "札幌レース場◯",
    type: "skill",
    desc: "「札幌レース場◯」のスキルヒントを得られる因子です",
  },
  {
    id: "oi_race_1",
    name: "大井レース場◯",
    type: "skill",
    desc: "「大井レース場◯」のスキルヒントを得られる因子です",
  },
  {
    id: "konkan_1",
    name: "根幹距離◯",
    type: "skill",
    desc: "「根幹距離◯」のスキルヒントを得られる因子です",
  },
  {
    id: "nakayama_race_1",
    name: "中山レース場○",
    type: "skill",
    desc: "「中山レース場○」のスキルヒントを得られる因子です",
  },
  {
    id: "tokyo_race_1",
    name: "東京レース場◯",
    type: "skill",
    desc: "「東京レース場◯」のスキルヒントを得られる因子です",
  },
  {
    id: "hanshin_race_1",
    name: "阪神レース場◯",
    type: "skill",
    desc: "「阪神レース場◯」のスキルヒントを得られる因子です",
  },
  {
    id: "ohitori_1",
    name: "おひとり様◯",
    type: "skill",
    desc: "「おひとり様◯」のスキルヒントを得られる因子です",
  },
  {
    id: "ryobaba_1",
    name: "良バ場◯",
    type: "skill",
    desc: "「良バ場◯」のスキルヒントを得られる因子です",
  },
  {
    id: "taiko_ishiki_1",
    name: "対抗意識◯",
    type: "skill",
    desc: "「対抗意識◯」のスキルヒントを得られる因子です",
  },
  {
    id: "mitiwaru_1",
    name: "道悪〇",
    type: "skill",
    desc: "「道悪〇」のスキルヒントを得られる因子です",
  },
  {
    id: "natsu_uma_1",
    name: "夏ウマ娘◯",
    type: "skill",
    desc: "「夏ウマ娘◯」のスキルヒントを得られる因子です",
  },
  {
    id: "huyu_uma_1",
    name: "冬ウマ娘◯",
    type: "skill",
    desc: "「冬ウマ娘◯」のスキルヒントを得られる因子です",
  },
  {
    id: "yukinohi_1",
    name: "雪の日◯",
    type: "skill",
    desc: "「雪の日◯」のスキルヒントを得られる因子です",
  },
  {
    id: "alone_wolf_1",
    name: "一匹狼",
    type: "skill",
    desc: "「一匹狼」のスキルヒントを得られる因子です",
  },
  {
    id: "aki_uma_1",
    name: "秋ウマ娘◯",
    type: "skill",
    desc: "「秋ウマ娘」のスキルヒントを得られる因子です",
  },
  {
    id: "migimawari",
    name: "右回り◯",
    type: "skill",
    desc: "「右回り◯」のスキルヒントを得られる因子です",
  },
  {
    id: "haru_uma_1",
    name: "春ウマ娘◯",
    type: "skill",
    desc: "「春ウマ娘◯」のスキルヒントを得られる因子です",
  },
  {
    id: "fukuhei_1",
    name: "伏兵◯",
    type: "skill",
    desc: "「伏兵◯」のスキルヒントを得られる因子です",
  },
  {
    id: "hidari_mawari_1",
    name: "左回り◯",
    type: "skill",
    desc: "「左回り◯」のスキルヒントを得られる因子です",
  },
  {
    id: "sympaty",
    name: "シンパシー",
    type: "skill",
    desc: "「シンパシー」のスキルヒントを得られる因子です",
  },
  {
    id: "senko_kotsu_1",
    name: "先行のコツ◯",
    type: "skill",
    desc: "「先行のコツ◯」のスキルヒントを得られる因子です",
  },
  {
    id: "uchiwaku_tokui_1",
    name: "内枠得意◯",
    type: "skill",
    desc: "「内枠得意◯」のスキルヒントを得られる因子です",
  },
  {
    id: "sotowaku_tokui_1",
    name: "外枠得意◯",
    type: "skill",
    desc: "「外枠得意◯」のスキルヒントを得られる因子です",
  },
  {
    id: "oikomi_kotsu_1",
    name: "追込のコツ◯",
    type: "skill",
    desc: "「追込のコツ◯」のスキルヒントを得られる因子です",
  },
  {
    id: "nige_kotsu_1",
    name: "逃げのコツ◯",
    type: "skill",
    desc: "「逃げのコツ◯」のスキルヒントを得られる因子です",
  },
  {
    id: "sashi_kotsu_1",
    name: "差しのコツ◯",
    type: "skill",
    desc: "「差しのコツ◯」のスキルヒントを得られる因子です",
  },
  {
    id: "kumori_1",
    name: "曇りの日◯",
    type: "skill",
    desc: "「曇りの日◯」のスキルヒントを得られる因子です",
  },
  {
    id: "hare_1",
    name: "晴れの日◯",
    type: "skill",
    desc: "「晴れの日◯」のスキルヒントを得られる因子です",
  },
  {
    id: "ame_1",
    name: "雨の日◯",
    type: "skill",
    desc: "「雨の日◯」のスキルヒントを得られる因子です",
  },
  {
    id: "racky_seven",
    name: "ラッキーセブン",
    type: "skill",
    desc: "「ラッキーセブン」のスキルヒントを得られる因子です",
  },
  {
    id: "hurishibori",
    name: "ふり絞り",
    type: "skill",
    desc: "「ふり絞り」のスキルヒントを得られる因子です",
  },
  {
    id: "kakuremino",
    name: "隠れ蓑",
    type: "skill",
    desc: "「隠れ蓑」のスキルヒントを得られる因子です",
  },
  {
    id: "three_seven",
    name: "スリーセブン",
    type: "skill",
    desc: "「スリーセブン」のスキルヒントを得られる因子です",
  },
  {
    id: "path_jozu",
    name: "パス上手",
    type: "skill",
    desc: "「パス上手」のスキルヒントを得られる因子です",
  },
  {
    id: "pace_keep",
    name: "ペースキープ",
    type: "skill",
    desc: "「ペースキープ」のスキルヒントを得られる因子です",
  },
  {
    id: "reisei",
    name: "冷静",
    type: "skill",
    desc: "「冷静」のスキルヒントを得られる因子です",
  },
  {
    id: "sho_kyukei",
    name: "小休憩",
    type: "skill",
    desc: "「小休憩」のスキルヒントを得られる因子です",
  },
  {
    id: "ikioi_makase",
    name: "勢い任せ",
    type: "skill",
    desc: "「勢い任せ」のスキルヒントを得られる因子です",
  },
  {
    id: "umagomi_reisei",
    name: "ウマ込み冷静",
    type: "skill",
    desc: "「ウマ込み冷静」のスキルヒントを得られる因子です",
  },
  {
    id: "karoyaka_step",
    name: "軽やかステップ",
    type: "skill",
    desc: "「軽やかステップ」のスキルヒントを得られる因子です",
  },
  {
    id: "stamina_keep",
    name: "スタミナキープ",
    type: "skill",
    desc: "「スタミナキープ」のスキルヒントを得られる因子です",
  },
  {
    id: "zento_yoyo",
    name: "前途洋々",
    type: "skill",
    desc: "「前途洋々」のスキルヒントを得られる因子です",
  },
  {
    id: "corner_kaifuku_1",
    name: "コーナー回復◯",
    type: "skill",
    desc: "「コーナー回復◯」のスキルヒントを得られる因子です",
  },
  {
    id: "koi_tsuiso",
    name: "好位追走",
    type: "skill",
    desc: "「好位追走」のスキルヒントを得られる因子です",
  },
  {
    id: "eiyo_hokyu",
    name: "栄養補給",
    type: "skill",
    desc: "「栄養補給」のスキルヒントを得られる因子です",
  },
  {
    id: "shinkokyu",
    name: "深呼吸",
    type: "skill",
    desc: "「深呼吸」のスキルヒントを得られる因子です",
  },
  {
    id: "yosumi",
    name: "様子見",
    type: "skill",
    desc: "「様子見」のスキルヒントを得られる因子です",
  },
  {
    id: "tyokusen_kaifuku",
    name: "直線回復",
    type: "skill",
    desc: "「直線回復」のスキルヒントを得られる因子です",
  },
  {
    id: "tenkai_ukagai",
    name: "展開窺い",
    type: "skill",
    desc: "「展開窺い」のスキルヒントを得られる因子です",
  },
  {
    id: "gekono_tanoshimi",
    name: "下校の楽しみ",
    type: "skill",
    desc: "「下校の楽しみ」のスキルヒントを得られる因子です",
  },
  {
    id: "koho_taki",
    name: "後方待機",
    type: "skill",
    desc: "「後方待機」のスキルヒントを得られる因子です",
  },
  {
    id: "betsubara_tank",
    name: "別腹タンク",
    type: "skill",
    desc: "「別腹タンク」のスキルヒントを得られる因子です",
  },
];
